### ISSUE TITLE
Error ..types/vue relative mddule not found in lib/main.js

### ISSUE THREAD

**Issue by rdhainaut** [ztytotoro/vue-cookies-ts#2]
After an installation of package, i have encountered this error: 

```
ERROR  Failed to compile with 1 errors                                                                                                                                                   
This relative module was not found:

* ../types/vue in ./node_modules/vue-cookies-ts/lib/main.js
Type checking and linting in progress...

Version: typescript 3.6.2, tslint 5.19.0
Time: 3895ms
```

**Comment by lidessen** [comment]
> After an installation of package, i have encountered this error:
> 
> ```
> ERROR  Failed to compile with 1 errors                                                                                                                                                   
> This relative module was not found:
> 
> * ../types/vue in ./node_modules/vue-cookies-ts/lib/main.js
> Type checking and linting in progress...
> 
> Version: typescript 3.6.2, tslint 5.19.0
> Time: 3895ms
> ```

Hi, I fixed this issue in version 1.5.17, thanks for using : )
