### ISSUE TITLE
vue ssr Unexpected identifier

### ISSUE THREAD

**Issue by GreenMashimaro** [ztytotoro/vue-cookies-ts#3]
vue-cookies-ts: 1.5.17

Hello, I have encountered a problem. When using vue ssr, when I visit the page, I will get an error.
![image](https://user-images.githubusercontent.com/23225539/66851365-2c1d2900-efad-11e9-92e8-ac166d0ddbb0.png)
![image](https://user-images.githubusercontent.com/23225539/66851452-5cfd5e00-efad-11e9-81cc-8f71e4b07c47.png)

I analyzed the reason, vue ssr will be introduced according to vue-ssr-server-bundle.json through node, vue-cookies-ts does not support the way common js import.
So it is best to support the default export to common js to support the introduction of node support.

**Comment by lidessen** [comment]
@GreenMashimaro New realease of 1.5.19 published, this issues should be fixed now

**Comment by GreenMashimaro** [comment]
thank you very much.
